### ISSUE TITLE
Fix release workflow to not put stable version into dev helm repo

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/operator-templating#133]
Scope: All operators out there using operator-templating
While releasing commons-operator 0.1.0 we (@razvan, @soenkeliebau and @sbernauer ) noticed that 0.1.0 was not only placed in stable, but also in dev.
```
$ stackablectl op desc commons
Operator:           commons
Stable versions:    0.1.0
Test versions:      0.1.0-pr31, 0.1.0-pr30, 0.1.0-pr29, 0.1.0-pr26, 0.1.0-pr25, 0.1.0-pr24, 0.1.0-pr23, 0.1.0-pr22, 0.1.0-pr20, 0.1.0-pr19, 0.1.0-pr18, 0.1.0-pr17, 0.1.0-pr16, 0.1.0-pr11, 0.1.0-pr10
Dev versions:       0.1.0, 0.1.0-nightly
```
This is because https://github.com/stackabletech/operator-templating/blob/399d160c92cd8f0eb0d37fb2824e95e1cdb518b7/template/.github/workflows/build.yml.j2#L88-L90 puts the chart in the dev Repo when:
* A push to the main branch is performed

As we merge the new version in the main branch (to then tag the commit - e.g. https://github.com/stackabletech/commons-operator/commit/b183c5fe3808ff91be1574073293a44d3f6bfd1b) the pipeline runs and puts 0.1.0 in the dev repo.
To fix this the pipeline must use the dev repo when
* A push to the main branch is performed
* **AND the versions ends with `-nightly`**

This new check has to be added

**Comment by backstreetkiwi** [comment]
Once this is merged and propagated into the Operators, I'll delete the remaining stable versions from the dev repos.
