### ISSUE TITLE
Integrate Nix/Tilt-based workflow from Secret-Operator

### ISSUE THREAD

**Issue by nightkr** [stackabletech/operator-templating#162]
[Secret-Operator](https://github.com/stackabletech/secret-operator/blob/main/Tiltfile) uses a build workflow based on [Nix](https://nixos.org/), [crate2nix](https://github.com/kolloch/crate2nix), and [Tilt](https://tilt.dev/), which lets us run operators inside of the Kubernetes environment while preserving a relatively tight edit-run feedback loop (compared to our production Docker images which rebuild everything from scratch every time).

I believe this workflow has proven helpful enough in Secret-Op that I would like to propose rolling this out for all operators.

At least initially, this would coexist with (rather than replace) the Dockerfiles that we build production images.

**Comment by soenkeliebau** [comment]
closed by #212
