### ISSUE TITLE
Templating Action is broken due to expired gpg key of github cli 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-templating#174]
Templating is currently not working as the step to install the GH cli in the container [fails](https://github.com/stackabletech/operator-templating/runs/8182091013?check_suite_focus=true).

This is due to https://github.com/cli/cli/issues/6175

A few options are mentioned in the comments for that issue, but at this moment there is no fix available.

Options are: 
1. Install unauthenticated package, but this gets credentials for our github account and makes changes to repos - the security impact if compromised might be severe
2. Download binary from gh releases page instead of using apt 

From browsing the issue it [seems](https://github.com/cli/cli/issues/6175#issuecomment-1235984381) like updating the expired key may not be happening anytime soon, if ever. Item 2 from the list above is the recommended solution for now and might turn into the only supported one soon.

I think we should go with option 2 to fix this.

**Comment by siegfriedweber** [comment]
I assigned this issue to me because I was already working on it to finish #175 and stackabletech/secret-operator#177.
