### ISSUE TITLE
Make bors optional when merging pull requests

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-templating#177]
We introduced bors for a variety of reasons a while ago, some of which are not applicable any more (amount of dependabot pull requests) - bors became mandatory and the only way to merge PRs at that time.

Bors has sometimes become an issue, as it is externally hosted and became unavailable, so we'd like to reduce our dependecy on it a bit.

We have decided to make bors optional for now and track how much we still use it. Some time down the road we can then see if we want to completely remove it.

This is done when:
- [ ] Github repositories have been reconfigured to allow either merging manually or via bors (mandatory checks should be taken into account for both methods)
- [ ] Automerge has been enabled for all repositories

**Comment by nightkr** [comment]
We no longer use Bors: https://github.com/stackabletech/issues/issues/380
