### ISSUE TITLE
Add pinning for cargo udeps

### ISSUE THREAD

**Issue by adwk67** [stackabletech/operator-templating#253]
The version of cargo udeps should be pinned and locked, so instead of [this line](https://github.com/stackabletech/operator-templating/blob/main/template/.github/workflows/build.yml.j2#L45):

`cargo install cargo-udeps`

we would have something like this, where udeps version depends on the rust version:

`cargo install --locked cargo-udeps@0.1.35`

**Comment by fhennig** [comment]
This ticket should also include how we will upgrade this version in the future (part of the release process/rust upgrade?)

**Comment by razvan** [comment]
Implemented in https://github.com/stackabletech/operator-templating/pull/257/files
