### ISSUE TITLE
GH Action publishes release artifacts when any tag is pushed

### ISSUE THREAD

**Issue by fhennig** [stackabletech/operator-templating#43]
The github release action publishes release artifacts (publishing to helm stable) when any tag is pushed.
https://github.com/stackabletech/operator-templating/blob/main/template/.github/workflows/publish_release_artifacts.yml.j2#L10

This should not be. Only when a tag is in main should anything actually be released.

**Comment by razvan** [comment]
Especially since we might switch to a Git workflow where we might have a release branch (or version branches for LTS purposes that might never be merged to main again).

**Comment by fhennig** [comment]
I just talked with Razvan and this is not an isolated issue, so I'll close it for now.
